# Generated by Django 3.0.5 on 2021-02-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=200)),
                ('confirmed', models.CharField(max_length=200)),
                ('discharged', models.CharField(max_length=200)),
                ('death', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
