# Generated by Django 3.0.5 on 2021-02-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total',
            name='day',
            field=models.IntegerField(),
        ),
    ]
