# Generated by Django 3.0.5 on 2021-02-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total', '0002_auto_20210207_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total',
            name='day',
            field=models.CharField(max_length=100),
        ),
    ]
