# Generated by Django 3.0.5 on 2021-02-14 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('total', '0003_auto_20210207_2105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Count',
        ),
    ]
